/* Detective Academy — standalone lesson logic. Content also lives in data/case017.json for easy editing. */
const CASE = {
  vocab:[['alibi','a story that shows where someone was when a crime happened','Jack says he has an alibi.'],['motive','a reason for doing something, especially a crime','Money was Daniel’s motive.'],['witness','a person who sees an event happen','The witness saw someone leave.'],['evidence','facts or objects that help prove something','The phone record is important evidence.'],['fingerprint','a mark made by the lines on a person’s finger','Police found a fingerprint on the cup.'],['suspect','a person police believe may have committed a crime','Emily is a possible suspect.'],['confess','to admit that you did something wrong','Will the murderer confess?'],['investigate','to try to discover the facts about a crime','Detectives investigate the library.']],
  quiz:[{q:'Which word means “a reason for committing a crime”?',a:'motive',o:['alibi','motive','witness']},{q:'Which word means “a person who saw something happen”?',a:'witness',o:['evidence','suspect','witness']},{q:'A story that proves you were somewhere else is an…',a:'alibi',o:['alibi','investigation','fingerprint']}],
  grammar:[{s:'Daniel’s phone records show that his call ended at 8:20, not 8:45. He ___ on the phone at 8:45.',a:"can't have been",o:['must have been','might have been',"can't have been"]},{s:'The coffee contains sleeping medicine. Someone ___ it into Arthur’s drink.',a:'must have put',o:['must have put','can’t have put','might have forgotten']},{s:'Emily left the restaurant for twenty minutes. She ___ to the manor, but we do not know.',a:'might have gone',o:['must have gone','might have gone',"can't have gone"]}],
  clues:{clock:['Broken clock','The clock stopped at 8:45 PM — but a neighbour heard a loud argument at 8:30.','Does the clock show the time of death, or was it damaged later?'],cup:['Coffee cup','Arthur’s coffee contains sleeping medicine. Sarah usually makes the coffee.','Sarah’s fingerprints are on the cup. Is that suspicious, or normal?'],phone:['Arthur’s phone','At 8:27 PM, Arthur received a message: “We need to talk. Tonight.” The phone was deleted at 9:00.','Who had access to his phone after the crime?'],knife:['Letter opener','A letter opener with Arthur’s blood was found under the desk. The fingerprints are unclear.','Could the weapon have been cleaned or planted?'],window:['Open window','One leather glove was found beside the open window. There are no signs of forced entry.','Why open the window if the murderer was already inside?'],print:['Muddy footprint','The footprint matches Jack’s gardening boots. It leads towards the library but not away from it.','Jack must have been near the library. Does that mean he is guilty?']},
  suspects:[['Emily Carter','Business partner','♟','Arthur refused to sell company shares. Emily could lose £2 million.','She says she was at a restaurant from 8:00 to 9:30.','A waiter saw her leave for about 20 minutes.'],['Jack Turner','Gardener','♜','Arthur planned to fire Jack next week.','He says he never entered the house.','His boots match the muddy print near the library.'],['Sarah Collins','Housekeeper','♛','Arthur was planning to dismiss her.','She says she was cleaning upstairs.','She made Arthur’s coffee and found the body.'],['Daniel Blackwood','Arthur’s son','♚','He would inherit the manor and a large fortune.','He says he was on the phone outside.','Phone records show his call ended at 8:20 PM.']],
  prompts:['Where were you between 8:20 and 8:50 PM?','Can anyone confirm your alibi?','Why did the evidence connect you to the library?','What was your relationship with Arthur Blackwood?','What did you mean when you said “We need to talk”?','Why should the jury believe you?','What might another suspect have been hiding?']
};
const state={done:new Set(JSON.parse(localStorage.getItem('da017progress')||'[]')),quiz:0,selected:'',board:[]};
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function updateProgress(){const n=state.done.size;$('#progressText').textContent=`${n} / 10 missions`;$('#progressBar').style.width=`${n*10}%`;document.querySelectorAll('[data-complete]').forEach(b=>{if(state.done.has(b.dataset.complete)) b.classList.add('complete')});localStorage.setItem('da017progress',JSON.stringify([...state.done]));}
function complete(id){state.done.add(id);updateProgress();}
function renderVocab(){ $('#vocabGrid').innerHTML=CASE.vocab.map(([w,d,e])=>`<article class="vocab-card" tabindex="0" role="button" aria-label="Flip ${w} card"><div><div class="vocab-face"><p class="eyebrow">Click to reveal</p><h3>${w}</h3><small>Say it. Predict the meaning.</small></div><div class="vocab-face back"><h3>${w}</h3><p>${d}</p><small>“${e}”</small></div></div></article>`).join('');document.querySelectorAll('.vocab-card').forEach(c=>{c.onclick=()=>c.classList.toggle('flipped');c.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')c.classList.toggle('flipped')}})}
function renderQuiz(){let x=CASE.quiz[state.quiz];$('#quizQuestion').textContent=x.q;$('#quizFeedback').textContent='';$('#quizOptions').innerHTML=x.o.map(o=>`<button data-answer="${o}">${o}</button>`).join('');document.querySelectorAll('#quizOptions button').forEach(b=>b.onclick=()=>{let good=b.dataset.answer===x.a;$('#quizFeedback').textContent=good?'Correct. Say a full example sentence.':'Try again — look back at your notebook.';if(good){state.quiz=(state.quiz+1)%CASE.quiz.length;setTimeout(renderQuiz,900)}})}
function renderGrammar(){$('#grammarQuestions').innerHTML=CASE.grammar.map((x,i)=>`<article class="grammar-question"><p>${x.s}</p><div class="answer-set">${x.o.map(o=>`<button data-right="${o===x.a}">${o}</button>`).join('')}</div></article>`).join('');document.querySelectorAll('.answer-set button').forEach(b=>b.onclick=()=>b.classList.add(b.dataset.right==='true'?'correct':'wrong'));}
function renderSuspects(){ $('#suspectGrid').innerHTML=CASE.suspects.map((s,i)=>`<button class="suspect-card" data-suspect="${i}"><div class="portrait">${s[2]}</div><h3>${s[0]}</h3><p>${s[1]}</p></button>`).join('');document.querySelectorAll('.suspect-card').forEach(b=>b.onclick=()=>showSuspect(+b.dataset.suspect)); }
function showSuspect(i){let s=CASE.suspects[i];document.querySelectorAll('.suspect-card').forEach(x=>x.classList.remove('active'));$(`[data-suspect="${i}"]`).classList.add('active');$('#suspectDetail').innerHTML=`<p class="eyebrow">Suspect file · ${esc(s[1])}</p><h3>${esc(s[0])}</h3><dl><dt>Motive</dt><dd>${esc(s[3])}</dd><dt>Alibi</dt><dd>${esc(s[4])}</dd><dt>Inconsistency</dt><dd>${esc(s[5])}</dd></dl><p><strong>Ask:</strong> What could this person have done during the missing time?</p>`;}
function showClue(k){let c=CASE.clues[k];$('#clueDetail').innerHTML=`<p class="eyebrow">Evidence log</p><h3>${c[0]}</h3><p>${c[1]}</p><p><strong>Discuss:</strong> ${c[2]}</p>`;}
function renderBoard(){let select=$('#boardSuspect');select.innerHTML='<option value="">Choose a suspect…</option>'+CASE.suspects.map((s,i)=>`<option value="${i}">${s[0]}</option>`).join('');select.onchange=()=>{let s=CASE.suspects[select.value];$('#boardFocus').textContent=s?`${s[0]} — ${s[1]}`:'Choose a suspect';state.board=[];paintBoard();};$('#boardEvidence').onclick=e=>{let b=e.target.closest('button');if(!b)return;let k=b.dataset.clue;state.board.includes(k)?state.board=state.board.filter(x=>x!==k):state.board.push(k);paintBoard()};$('#clearBoard').onclick=()=>{state.board=[];paintBoard()};paintBoard();}
function paintBoard(){$('#boardEvidence').innerHTML=Object.entries(CASE.clues).map(([k,c])=>`<button class="evidence-pin ${state.board.includes(k)?'active':''}" data-clue="${k}">${c[0]}<br><small>${state.board.includes(k)?'CONNECTED':'click to connect'}</small></button>`).join('');$('#boardNote').textContent=state.board.length?`${state.board.length} clue${state.board.length>1?'s':''} connected. Explain why each one supports your theory.`:'Tip: a clue can support a theory, but it does not always prove it.';}
function renderJury(){ $('#juryGrid').innerHTML=CASE.suspects.map((s,i)=>`<button class="jury-option" data-vote="${i}"><b>${s[0]}</b><span>${s[1]}</span></button>`).join('');document.querySelectorAll('.jury-option').forEach(b=>b.onclick=()=>{state.selected=+b.dataset.vote;document.querySelectorAll('.jury-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});}
function teacher(){let answers=CASE.grammar.map(x=>`<li>${x.a}</li>`).join('');$('#teacherContent').innerHTML=`<div class="teacher-grid"><article><h3>Lesson route (80–90 min)</h3><ul><li>Briefing + warm-up: 13 min</li><li>Vocabulary + quick check: 15 min</li><li>Grammar: 15 min</li><li>Scene + suspects: 24 min</li><li>Interrogation + board: 20 min</li><li>Jury + reveal: 10 min</li></ul></article><article><h3>Grammar answers</h3><ol>${answers}</ol><p>Accept alternatives if the modal meaning is logical.</p></article><article><h3>Solution</h3><p><strong>Daniel</strong> is guilty. His call ended at 8:20; he had motive, opportunity and a false alibi. He drugged the coffee and killed Arthur when Arthur threatened to change his will.</p></article><article><h3>Teaching notes</h3><p>Keep the final reveal closed. Encourage evidence-based language rather than “I think”. Strong groups can create an alternative theory before the reveal.</p></article></div>`;$('#teacherDialog').showModal();}
function setup(){renderVocab();renderQuiz();renderGrammar();renderSuspects();renderBoard();renderJury();updateProgress();document.querySelectorAll('.mission-button').forEach(b=>b.onclick=()=>complete(b.dataset.complete));document.querySelectorAll('.object-card').forEach(b=>b.onclick=()=>$('#warmupPrompt').textContent=b.dataset.prompt);document.querySelectorAll('.clue').forEach(b=>b.onclick=()=>showClue(b.dataset.clue));$('#drawPrompt').onclick=()=>$('#interrogationPrompt').textContent=CASE.prompts[Math.floor(Math.random()*CASE.prompts.length)];let running=false,seconds=90,timer;$('#startTimer').onclick=()=>{if(running)return;running=true;seconds=90;clearInterval(timer);timer=setInterval(()=>{seconds--;$('#timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;if(seconds<=0){clearInterval(timer);running=false;$('#timer').textContent='Time! Switch roles.'}},1000)};$('#submitVerdict').onclick=()=>{let reason=$('#reasoning').value.trim();if(state.selected==='')return $('#verdictFeedback').textContent='Choose a suspect before submitting.';if(reason.length<25)return $('#verdictFeedback').textContent='Add at least one full reason using evidence.';let chosen=CASE.suspects[state.selected][0];$('#verdictFeedback').textContent=chosen==='Daniel Blackwood'?'A compelling verdict. Open the sealed envelope when the class is ready.':'Your jury has a theory. Before the reveal, check Daniel’s phone record again.';complete('jury')};$('#openReveal').onclick=()=>{$('#revealCard').hidden=false;complete('reveal');$('#revealCard').scrollIntoView({behavior:'smooth',block:'center'})};$('#teacherButton').onclick=teacher;$('.close-dialog').onclick=()=>$('#teacherDialog').close();}
setup();
